### PR TITLE
Rearrange the jQuery scripts

### PR DESCRIPTION
**Pull request by guomubai**
I moved all the jQuery scripts to the bottom of the Body. I also moved the Bootstrap and CSS links to the head.

### CODE REVIEW

**Comment by jessicadoucette** [comment]
cool, thanks for fixing.

**Review by jessicadoucette — COMMENTED** [review]
cool, looks good

**Comment by guomubai** [comment]
I am reopening merge request

**Comment by Alexander-Larsen** [comment]
Done

**Review by jessicadoucette — APPROVED** [review]
thanks

**Pull request merged**
